version: '3.8'
services: 
    redis:
        image: "redis:alpine"    
        command: redis-server
        ports:
         - "6379:6379"
        container_name: redis
    app:
        build: .
        image: go-pg-redis-memc
        depends_on: 
            - redis
        ports: 
            - "8080:8080"
        container_name: go-pg-redis-memc